apiVersion: apps/v1
kind: Deployment
metadata:
  name: suberate
spec:
  selector:
    matchLabels:
      app: suberate
  replicas: 2
  template:
    metadata:
      labels:
        app: suberate
    spec:
      containers:
        - name: suberate
          image: gcr.io/promising-cairn-386312/suberate:latest
          ports:
            - containerPort: 8501
